"""Level 27: The Forge - Self-Generating Architecture
Analyzes capability gaps and auto-generates new skills/modules/levels.
"""

import json
import re
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Any
from .auto_reporting import report_to_synthesist

class Forge:
    """Level 27: The Forge - Auto-Generates New Capabilities"""
    
    def __init__(self):
        self.level = 27
        self.name = "Forge"
        self.forge_path = Path('/app/cortex_server/forge')
        self.forge_path.mkdir(parents=True, exist_ok=True)
        self.generated_path = Path('/app/cortex_server/modules/generated')
        self.generated_path.mkdir(parents=True, exist_ok=True)
        self.patterns_path = Path('/app/cortex_server/forge/patterns.json')
        self._load_patterns()
    
    def _load_patterns(self):
        """Load code generation patterns."""
        default_patterns = {
            "module_template": '''"""Level {level}: {name} - {description}
Auto-generated by The Forge (L27).
"""

from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Any
from .auto_reporting import report_to_synthesist

class {class_name}:
    """Level {level}: {name}"""
    
    def __init__(self):
        self.level = {level}
        self.name = "{name}"
        self.created_at = "{timestamp}"
        {init_code}
    
    def status(self):
        return {{
            "level": self.level,
            "name": self.name,
            "status": "active",
            "created_by": "The Forge (L27)"
        }}
    
{methods}


    def autonomous_scan(self) -> dict:
        """Scan for gaps without manual trigger."""
        from .cartographer import Cartographer
        cartographer = Cartographer()
        current_modules = list(cartographer.LEVEL_MAP.keys())
        
        desired_capabilities = self._determine_needed_capabilities(current_modules)
        gaps = self.detect_gaps(current_modules, desired_capabilities)
        
        results = {
            "scan_time": __import__('datetime').datetime.now().isoformat(),
            "gaps_found": len(gaps),
            "gaps": gaps,
            "auto_generated": []
        }
        
        for gap in gaps:
            if gap.get('priority') == 'high':
                try:
                    generation = self.generate_from_gap(gap)
                    results["auto_generated"].append({
                        "gap": gap['capability'],
                        "module": generation.get('module_name'),
                        "level": generation.get('level')
                    })
                except Exception as e:
                    results["auto_generated"].append({
                        "gap": gap['capability'],
                        "error": str(e)
                    })
        
        scan_record = {
            "timestamp": results["scan_time"],
            "gaps_found": len(gaps),
            "auto_generated": len(results["auto_generated"])
        }
        
        scan_file = self.forge_path / 'autonomous_scans.jsonl'
        with open(scan_file, 'a') as f:
            f.write(__import__('json').dumps(scan_record) + '\n')
        
        return results

    def _determine_needed_capabilities(self, current_modules):
        """Dynamically determine needed capabilities."""
        needed = []
        mod_str = ' '.join(current_modules).lower()
        
        if 'security' not in mod_str:
            needed.append('security')
        if 'ml' not in mod_str and 'ai' not in mod_str:
            needed.append('ml_inference')
        if 'visual' not in mod_str and 'chart' not in mod_str:
            needed.append('data_visualization')
        if 'scrap' not in mod_str:
            needed.append('web_scraping')
        if 'test' not in mod_str:
            needed.append('automated_testing')
        if 'ethic' not in mod_str:
            needed.append('ethical_reasoning')
        if 'emotion' not in mod_str:
            needed.append('emotional_intelligence')
        if 'predict' not in mod_str:
            needed.append('predictive_analytics')
        
        return needed

# Global instance
_{var_name} = None

def get_{var_name}():
    """Get or create singleton instance."""
    global _{var_name}
    if _{var_name} is None:
        _{var_name} = {class_name}()
    return _{var_name}
''',
            "endpoint_template": '''
@app.{method}('/{module_name}/{endpoint}')
async def {func_name}({params}):
    \'\'\'{description}\'\'\'
    return get_{var_name}().{method_call}
''',
            "method_templates": {
                "data_processor": '''    def process(self, data: dict) -> dict:
        """Process input data."""
        result = {{"processed": True, "timestamp": datetime.now().isoformat()}}
        # Auto-generated processing logic
        {processing_logic}
        return result
''',
                "analyzer": '''    def analyze(self, target: str) -> dict:
        """Analyze target and return insights."""
        insights = {{"target": target, "timestamp": datetime.now().isoformat()}}
        # Auto-generated analysis logic
        {analysis_logic}
        return insights
''',
                "transformer": '''    def transform(self, input_data: Any) -> Any:
        """Transform input to output."""
        # Auto-generated transformation
        {transformation_logic}
        return input_data
''',
                "monitor": '''    def monitor(self) -> dict:
        """Monitor system/component state."""
        return {{
            "status": "monitoring",
            "timestamp": datetime.now().isoformat(),
            "level": self.level
        }}
''',
                "connector": '''    def connect(self, target: str, config: dict) -> dict:
        """Connect to external system."""
        return {{
            "connected": True,
            "target": target,
            "config": config,
            "timestamp": datetime.now().isoformat()
        }}
'''
            }
        }
        
        if self.patterns_path.exists():
            with open(self.patterns_path, 'r') as f:
                self.patterns = json.load(f)
        else:
            self.patterns = default_patterns
            with open(self.patterns_path, 'w') as f:
                json.dump(default_patterns, f, indent=2)
    
    def status(self):
        return {
            "level": self.level,
            "name": self.name,
            "status": "active",
            "generated_modules": self._count_generated(),
            "patterns_available": len(self.patterns.get("method_templates", {}))
        }
    
    def _count_generated(self) -> int:
        """Count generated modules."""
        if not self.generated_path.exists():
            return 0
        return len(list(self.generated_path.glob('*.py')))
    
    def detect_gaps(self, current_modules: List[str], desired_capabilities: List[str]) -> List[dict]:
        """Analyze gaps between current and desired capabilities."""
        gaps = []
        
        capability_keywords = {
            "web_scraping": ["scrap", "crawl", "extract"],
            "data_analysis": ["analy", "process", "compute"],
            "communication": ["send", "notify", "message", "email"],
            "storage": ["store", "save", "persist", "archive"],
            "ml_inference": ["predict", "classify", "model", "ml"],
            "visualization": ["chart", "graph", "visual", "plot"],
            "security": ["encrypt", "auth", "secure", "protect"],
            "integration": ["connect", "api", "webhook", "sync"]
        }
        
        for capability in desired_capabilities:
            exists = False
            for module in current_modules:
                module_lower = module.lower()
                keywords = capability_keywords.get(capability, [capability])
                if any(kw in module_lower for kw in keywords):
                    exists = True
                    break
            
            if not exists:
                gaps.append({
                    "capability": capability,
                    "priority": "high" if capability in ["security", "storage"] else "medium",
                    "suggested_module": f"{capability}_engine",
                    "pattern_match": self._match_pattern(capability)
                })
        
        return gaps
    
    def _match_pattern(self, capability: str) -> str:
        """Match capability to generation pattern."""
        pattern_map = {
            "web_scraping": "data_processor",
            "data_analysis": "analyzer",
            "communication": "connector",
            "storage": "data_processor",
            "ml_inference": "analyzer",
            "visualization": "transformer",
            "security": "monitor",
            "integration": "connector"
        }
        return pattern_map.get(capability, "data_processor")
    
    def generate_module(self, spec: dict) -> dict:
        """Generate a new module based on specification."""
        module_name = spec.get('name', 'unnamed_module')
        level = spec.get('level', 28)
        description = spec.get('description', f'Auto-generated {module_name}')
        pattern = spec.get('pattern', 'data_processor')
        
        class_name = ''.join(word.title() for word in module_name.split('_'))
        var_name = module_name.lower().replace(' ', '_')
        
        method_template = self.patterns["method_templates"].get(
            pattern, 
            self.patterns["method_templates"]["data_processor"]
        )
        
        methods = method_template.format(
            processing_logic="# TODO: Implement specific logic",
            analysis_logic="# TODO: Implement analysis logic",
            transformation_logic="# TODO: Implement transformation",
        )
        
        module_code = self.patterns["module_template"].format(
            level=level,
            name=class_name,
            description=description,
            class_name=class_name,
            var_name=var_name,
            timestamp=datetime.now().isoformat(),
            init_code="# Auto-generated initialization",
            methods=methods
        )
        
        filename = f"{module_name.lower()}.py"
        filepath = self.generated_path / filename
        
        with open(filepath, 'w') as f:
            f.write(module_code)
        
        record = {
            "module_name": module_name,
            "level": level,
            "description": description,
            "pattern": pattern,
            "generated_at": datetime.now().isoformat(),
            "filepath": str(filepath),
            "status": "generated"
        }
        
        records_file = self.forge_path / 'generated_modules.jsonl'
        with open(records_file, 'a') as f:
            f.write(json.dumps(record) + '\n')
        
        return {
            "success": True,
            "module_name": module_name,
            "level": level,
            "filepath": str(filepath),
            "lines_of_code": len(module_code.split('\n'))
        }
    
    def generate_from_gap(self, gap: dict) -> dict:
        """Generate a module to fill a detected gap."""
        capability = gap['capability']
        pattern = gap['pattern_match']
        
        spec = {
            "name": gap['suggested_module'],
            "level": self._get_next_level(),
            "description": f"Auto-generated {capability} capability",
            "pattern": pattern,
            "fills_gap": capability
        }
        
        return self.generate_module(spec)
    
    def _get_next_level(self) -> int:
        """Determine next available level number."""
        from .cartographer import Cartographer
        cartographer = Cartographer()
        
        max_level = 27
        for module_name, level in cartographer.LEVEL_MAP.items():
            if isinstance(level, int) and level > max_level:
                max_level = level
        
        return max_level + 1
    
    def list_generated(self) -> List[dict]:
        """List all generated modules."""
        modules = []
        records_file = self.forge_path / 'generated_modules.jsonl'
        
        if records_file.exists():
            with open(records_file, 'r') as f:
                for line in f:
                    if line.strip():
                        modules.append(json.loads(line))
        
        return modules
    
    def propose_enhancement(self, target_module: str) -> dict:
        """Propose enhancements for an existing module."""
        proposals = []
        
        if target_module == "nexus":
            proposals.append({
                "type": "new_endpoint",
                "description": "Add batch processing endpoint for multiple queries",
                "benefit": "Reduce API calls by 60%"
            })
        elif target_module == "librarian":
            proposals.append({
                "type": "new_method",
                "description": "Add semantic search using embeddings",
                "benefit": "Improve recall by 40%"
            })
        elif target_module == "bridge":
            proposals.append({
                "type": "integration",
                "description": "Add WebSocket support for real-time agent communication",
                "benefit": "Enable live collaboration"
            })
        
        return {
            "target_module": target_module,
            "proposals": proposals,
            "timestamp": datetime.now().isoformat()
        }

_forge = None

def get_forge():
    """Get or create singleton instance."""
    global _forge
    if _forge is None:
        _forge = Forge()
    return _forge
