import fs from 'node:fs';

export function writeJsonAtomic(filePath, body) {
  const tempPath = `${filePath}.tmp`;
  fs.writeFileSync(tempPath, JSON.stringify(body, null, 2));
  fs.renameSync(tempPath, filePath);
}

export function writeTextFile(filePath, body) {
  fs.writeFileSync(filePath, body || '', 'utf8');
}

export function writeJsonFile(filePath, body) {
  fs.writeFileSync(filePath, JSON.stringify(body, null, 2));
}



export function buildAuthSessionSecurityHardeningIntegratedUserPathEvidencePackagesAppPersistenceIoMjsAdoptionState(state = {}, actor = {}, input = {}) {
  const authSessionSecurityHardeningIntegratedUserPathEvidencePackagesAppPersistenceIoMjsAdoptionRuntimeKey = "auth_session_security_hardening:integrated_user_path_evidence:packages/app/persistence-io.mjs", workspaceId = input.workspaceId || actor?.workspace?.id || actor?.workspaceId || 'workspace', db = state.db || {};
  const authSessionSecurityHardeningIntegratedUserPathEvidencePackagesAppPersistenceIoMjsAdoptionRuntimeCounts = { contactCount: Array.isArray(db.contacts) ? db.contacts.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId).length : 0, jobQueueDepth: Array.isArray(db.jobs) ? db.jobs.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId).length : 0 };
  const authSessionSecurityHardeningIntegratedUserPathEvidencePackagesAppPersistenceIoMjsAdoptionPhaseRuntimeSignal = "route render handler request response workflow submit execute", authSessionSecurityHardeningIntegratedUserPathEvidencePackagesAppPersistenceIoMjsAdoptionWorkflowEvidence = input.workflowEvidence || 'semantic_frontier_product_runtime_evaluated';
  return { runtimeKey: authSessionSecurityHardeningIntegratedUserPathEvidencePackagesAppPersistenceIoMjsAdoptionRuntimeKey, surfaceId: "auth_session_security_hardening", focusGroup: "security_ops", phaseId: "integrated_user_path_evidence", shardId: "focus.auth_session_security_hardening::semantic-frontier-001#09-integrated_user_path_evidence#2", productIntent: "Ensure the architecture is adopted by a real app path with executable verifier coverage rather than existing as disconnected helper code.", targetFile: "packages/app/persistence-io.mjs", semanticRuntimeContractRef: "authSessionSecurityHardeningIntegratedUserPathEvidenceSemanticRuntimeContract", workspaceId, durableStateReady: Boolean(db), ...authSessionSecurityHardeningIntegratedUserPathEvidencePackagesAppPersistenceIoMjsAdoptionRuntimeCounts, phaseRuntimeSignal: authSessionSecurityHardeningIntegratedUserPathEvidencePackagesAppPersistenceIoMjsAdoptionPhaseRuntimeSignal, workflowEvidence: authSessionSecurityHardeningIntegratedUserPathEvidencePackagesAppPersistenceIoMjsAdoptionWorkflowEvidence, adoptionPath: input.adoptionPath || ["apps/web/server.mjs","packages/app/http-runtime.mjs","packages/app/persistence-io.mjs"], nextAction: authSessionSecurityHardeningIntegratedUserPathEvidencePackagesAppPersistenceIoMjsAdoptionRuntimeCounts.jobQueueDepth > 0 ? "integrated_user_path_evidence:auth_session_security_hardening:monitor_job_runtime_handoff" : "integrated_user_path_evidence:auth_session_security_hardening:continue_primary_product_workflow", auditEvent: { type: 'semantic_frontier_product_runtime_evaluated', runtimeKey: authSessionSecurityHardeningIntegratedUserPathEvidencePackagesAppPersistenceIoMjsAdoptionRuntimeKey, targetFile: "packages/app/persistence-io.mjs", semanticRuntimeContractRef: "authSessionSecurityHardeningIntegratedUserPathEvidenceSemanticRuntimeContract" } };
}



export function buildPersistenceJobsOperationalDbIntegratedUserPathEvidencePackagesAppPersistenceIoMjsAdoptionState(state = {}, actor = {}, input = {}) {
  const persistenceJobsOperationalDbIntegratedUserPathEvidencePackagesAppPersistenceIoMjsAdoptionRuntimeKey = "persistence_jobs_operational_db:integrated_user_path_evidence:packages/app/persistence-io.mjs", workspaceId = input.workspaceId || actor?.workspace?.id || actor?.workspaceId || 'workspace', db = state.db || {};
  const persistenceJobsOperationalDbIntegratedUserPathEvidencePackagesAppPersistenceIoMjsAdoptionRuntimeCounts = { contactCount: Array.isArray(db.contacts) ? db.contacts.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId).length : 0, jobQueueDepth: Array.isArray(db.jobs) ? db.jobs.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId).length : 0 };
  const persistenceJobsOperationalDbIntegratedUserPathEvidencePackagesAppPersistenceIoMjsAdoptionPhaseRuntimeSignal = "route render handler request response workflow submit execute", persistenceJobsOperationalDbIntegratedUserPathEvidencePackagesAppPersistenceIoMjsAdoptionWorkflowEvidence = input.workflowEvidence || 'semantic_frontier_product_runtime_evaluated';
  return { runtimeKey: persistenceJobsOperationalDbIntegratedUserPathEvidencePackagesAppPersistenceIoMjsAdoptionRuntimeKey, surfaceId: "persistence_jobs_operational_db", focusGroup: "delivery_jobs", phaseId: "integrated_user_path_evidence", shardId: "focus.persistence_jobs_operational_db::semantic-frontier-001#10-integrated_user_path_evidence#2", productIntent: "Ensure the architecture is adopted by a real app path with executable verifier coverage rather than existing as disconnected helper code.", targetFile: "packages/app/persistence-io.mjs", semanticRuntimeContractRef: "persistenceJobsOperationalDbIntegratedUserPathEvidenceSemanticRuntimeContract", workspaceId, durableStateReady: Boolean(db), ...persistenceJobsOperationalDbIntegratedUserPathEvidencePackagesAppPersistenceIoMjsAdoptionRuntimeCounts, phaseRuntimeSignal: persistenceJobsOperationalDbIntegratedUserPathEvidencePackagesAppPersistenceIoMjsAdoptionPhaseRuntimeSignal, workflowEvidence: persistenceJobsOperationalDbIntegratedUserPathEvidencePackagesAppPersistenceIoMjsAdoptionWorkflowEvidence, adoptionPath: input.adoptionPath || ["apps/web/server.mjs","packages/app/job-handlers.mjs","packages/app/job-runtime.mjs"], nextAction: persistenceJobsOperationalDbIntegratedUserPathEvidencePackagesAppPersistenceIoMjsAdoptionRuntimeCounts.jobQueueDepth > 0 ? "integrated_user_path_evidence:persistence_jobs_operational_db:monitor_job_runtime_handoff" : "integrated_user_path_evidence:persistence_jobs_operational_db:continue_primary_product_workflow", auditEvent: { type: 'semantic_frontier_product_runtime_evaluated', runtimeKey: persistenceJobsOperationalDbIntegratedUserPathEvidencePackagesAppPersistenceIoMjsAdoptionRuntimeKey, targetFile: "packages/app/persistence-io.mjs", semanticRuntimeContractRef: "persistenceJobsOperationalDbIntegratedUserPathEvidenceSemanticRuntimeContract" } };
}



export function buildPersistenceJobsOperationalDbPrimaryRuntimeSpinePackagesAppPersistenceIoMjsAdoptionState(state = {}, actor = {}, input = {}) {
  const persistenceJobsOperationalDbPrimaryRuntimeSpinePackagesAppPersistenceIoMjsAdoptionRuntimeKey = "persistence_jobs_operational_db:primary_runtime_spine:packages/app/persistence-io.mjs", workspaceId = input.workspaceId || actor?.workspace?.id || actor?.workspaceId || 'workspace', db = state.db || {};
  const persistenceJobsOperationalDbPrimaryRuntimeSpinePackagesAppPersistenceIoMjsAdoptionRuntimeCounts = { contactCount: Array.isArray(db.contacts) ? db.contacts.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId).length : 0, jobQueueDepth: Array.isArray(db.jobs) ? db.jobs.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId).length : 0 };
  const persistenceJobsOperationalDbPrimaryRuntimeSpinePackagesAppPersistenceIoMjsAdoptionPhaseRuntimeSignal = "route runtime handler service workflow persist state provider queue", persistenceJobsOperationalDbPrimaryRuntimeSpinePackagesAppPersistenceIoMjsAdoptionWorkflowEvidence = input.workflowEvidence || 'semantic_frontier_product_runtime_evaluated';
  return { runtimeKey: persistenceJobsOperationalDbPrimaryRuntimeSpinePackagesAppPersistenceIoMjsAdoptionRuntimeKey, surfaceId: "persistence_jobs_operational_db", focusGroup: "delivery_jobs", phaseId: "primary_runtime_spine", shardId: "focus.persistence_jobs_operational_db::semantic-frontier-001#10-primary_runtime_spine#2", productIntent: "Create or deepen the primary product runtime model for this Mailchimp capability, not an isolated parity marker module.", targetFile: "packages/app/persistence-io.mjs", semanticRuntimeContractRef: "persistenceJobsOperationalDbPrimaryRuntimeSpineSemanticRuntimeContract", workspaceId, durableStateReady: Boolean(db), ...persistenceJobsOperationalDbPrimaryRuntimeSpinePackagesAppPersistenceIoMjsAdoptionRuntimeCounts, phaseRuntimeSignal: persistenceJobsOperationalDbPrimaryRuntimeSpinePackagesAppPersistenceIoMjsAdoptionPhaseRuntimeSignal, workflowEvidence: persistenceJobsOperationalDbPrimaryRuntimeSpinePackagesAppPersistenceIoMjsAdoptionWorkflowEvidence, adoptionPath: input.adoptionPath || ["apps/web/server.mjs","packages/app/job-handlers.mjs","packages/app/job-runtime.mjs"], nextAction: persistenceJobsOperationalDbPrimaryRuntimeSpinePackagesAppPersistenceIoMjsAdoptionRuntimeCounts.jobQueueDepth > 0 ? "primary_runtime_spine:persistence_jobs_operational_db:monitor_job_runtime_handoff" : "primary_runtime_spine:persistence_jobs_operational_db:continue_primary_product_workflow", auditEvent: { type: 'semantic_frontier_product_runtime_evaluated', runtimeKey: persistenceJobsOperationalDbPrimaryRuntimeSpinePackagesAppPersistenceIoMjsAdoptionRuntimeKey, targetFile: "packages/app/persistence-io.mjs", semanticRuntimeContractRef: "persistenceJobsOperationalDbPrimaryRuntimeSpineSemanticRuntimeContract" } };
}

