#!/usr/bin/env bash
set -euo pipefail
cd /root/clawd
export ORACLE_EXECUTOR_AGENT="${ORACLE_EXECUTOR_AGENT:-oracle}"
export ORACLE_EXECUTOR_SESSION_MODE="${ORACLE_EXECUTOR_SESSION_MODE:-ephemeral}"
export ORACLE_EXECUTOR_SESSION_BUCKET_MINUTES="${ORACLE_EXECUTOR_SESSION_BUCKET_MINUTES:-60}"
export ORACLE_EXECUTOR_SESSION_RETENTION_COUNT="${ORACLE_EXECUTOR_SESSION_RETENTION_COUNT:-300}"
export ORACLE_EXECUTOR_SESSION_RETENTION_DAYS="${ORACLE_EXECUTOR_SESSION_RETENTION_DAYS:-7}"
export ORACLE_EXECUTOR_SESSION_CLEANUP_INTERVAL_SECONDS="${ORACLE_EXECUTOR_SESSION_CLEANUP_INTERVAL_SECONDS:-1800}"
pkill -f 'uvicorn deploy.oracle_executor:app' >/dev/null 2>&1 || true
exec python3 -m uvicorn deploy.oracle_executor:app --host 0.0.0.0 --port 18999
