import { automationRunSummary, campaignGrowthFunnel } from '../domain-growth.mjs';
import { page } from '../view.mjs';
import { analyticsSeries, workspaceSummary } from '../domain-growth.mjs';
import { campaignReportDetailSummary } from '../domain-campaigns.mjs';
import { revenueSummary } from '../domain-commerce-revenue.mjs';
import { buildTelemetryPipelineSnapshot, refreshReportingTelemetryPipeline } from '../analytics-events.mjs';
import { csv, redirect, text } from '../utils.mjs';

export function registerReportRoutes(router, deps) {
  const { requireAuth } = deps;

  router.register('GET', '/reports', async ({ state, req, res }) => {
    const actor = requireAuth(state, req, res); if (!actor) return; const summary = workspaceSummary(state, actor.workspace.id); const trends = analyticsSeries(state, actor.workspace.id); const revenue = revenueSummary(state, actor.workspace.id); const activeCampaigns = state.db.campaigns.filter((entry) => entry.workspaceId === actor.workspace.id && ['queued', 'scheduled', 'sent'].includes(entry.status)); const telemetry = buildTelemetryPipelineSnapshot(state, actor.workspace.id);
    text(res, 200, page('Reports overview', actor, `<div class="grid"><div class="card"><h3>Workspace metrics</h3><pre>${JSON.stringify(summary, null, 2)}</pre></div><div class="card"><h3>Trend cards</h3><ul>${trends.map((entry) => `<li>${entry.label}: ${entry.value}</li>`).join('')}</ul></div><div class="card"><h3>Revenue attribution</h3><pre>${JSON.stringify(revenue, null, 2)}</pre></div><div class="card"><h3>Telemetry pipeline</h3><p>Status: ${telemetry.freshness.status}</p><p>Events: ${telemetry.eventCount}</p><p>Pipeline runs: ${telemetry.pipelineRunCount}</p><p>Lineage rows: ${telemetry.lineageRowCount}</p><p><a href="/reports/telemetry">Open telemetry pipeline</a></p></div><div class="card"><h3>Current-product reports</h3><p><a href="/reports/optimization">Optimization outcomes</a></p><p><a href="/reports/omnichannel">Omnichannel performance</a></p></div><div class="card"><h3>Report integrity</h3><p>Active send surfaces: ${activeCampaigns.length}</p><p>Published forms: ${summary.publishedForms}</p><p>Published landing pages: ${summary.publishedLandingPages}</p><p><a href="/api/reports/summary">Open API summary</a></p></div></div><div class="card"><h3>Report drilldown</h3><ul>${state.db.campaigns.filter((entry) => entry.workspaceId === actor.workspace.id).map((campaign) => `<li><a href="/reports/campaigns/${campaign.id}">${campaign.name}</a>${state.db.campaignExperiments?.find((experiment) => experiment.campaignId === campaign.id) ? ` · <a href="/reports/experiments/${state.db.campaignExperiments.find((experiment) => experiment.campaignId === campaign.id).id}">experiment</a>` : ''}</li>`).join('')}${state.db.automations.filter((entry) => entry.workspaceId === actor.workspace.id).map((automation) => `<li><a href="/reports/automations/${automation.id}">${automation.name}</a></li>`).join('')}</ul></div>`));
  });

  router.register('GET', '/reports/telemetry', async ({ state, req, res }) => {
    const actor = requireAuth(state, req, res); if (!actor) return;
    const latest = (state.db.reportingTelemetrySnapshots || []).find((entry) => entry.workspaceId === actor.workspace.id) || buildTelemetryPipelineSnapshot(state, actor.workspace.id);
    text(res, 200, page('Reporting telemetry pipeline', actor, `<div class="grid"><div class="card"><h3>Pipeline freshness</h3><p>Status: ${latest.freshness.status}</p><p>Latest event: ${latest.freshness.latestEventAt || 'none'}</p><p>Latest pipeline run: ${latest.freshness.latestPipelineRunAt || 'none'}</p><form method="post" action="/reports/telemetry/refresh"><button>Refresh telemetry rollup</button></form></div><div class="card"><h3>Source counts</h3><pre>${JSON.stringify(latest.sourceCounts, null, 2)}</pre></div><div class="card"><h3>Event types</h3><pre>${JSON.stringify(latest.eventTypeCounts, null, 2)}</pre></div><div class="card"><h3>Attribution</h3><pre>${JSON.stringify(latest.attribution, null, 2)}</pre></div></div><div class="card"><h3>Campaign telemetry rollups</h3><table><tr><th>Campaign</th><th>Status</th><th>Sent</th><th>Open rate</th><th>Click rate</th><th>Events</th></tr>${latest.campaignRollups.map((row) => `<tr><td>${row.name}</td><td>${row.status}</td><td>${row.sent}</td><td>${row.openRate}%</td><td>${row.clickRate}%</td><td>${row.eventCount}</td></tr>`).join('') || '<tr><td colspan="6">No campaign rollups yet.</td></tr>'}</table></div><div class="card"><h3>Lineage preview</h3><table><tr><th>Event</th><th>Source</th><th>Observed</th><th>Pipeline run</th></tr>${latest.lineagePreview.map((row) => `<tr><td>${row.eventId}</td><td>${row.source}</td><td>${row.observedAt}</td><td>${row.pipelineRunId}</td></tr>`).join('') || '<tr><td colspan="4">No telemetry lineage yet.</td></tr>'}</table></div>`));
  });

  router.register('POST', '/reports/telemetry/refresh', async ({ state, req, res }) => {
    const actor = requireAuth(state, req, res); if (!actor) return;
    refreshReportingTelemetryPipeline(state, actor);
    redirect(res, '/reports/telemetry');
  });

  router.register('GET', '/reports/campaigns/:id', async ({ state, req, params, res }) => {
    const actor = requireAuth(state, req, res); if (!actor) return; const campaign = state.db.campaigns.find((entry) => entry.id === params.id && entry.workspaceId === actor.workspace.id); const funnel = campaignGrowthFunnel(state, campaign.id); const detail = campaignReportDetailSummary(state, campaign);
    text(res, 200, page(`Campaign report: ${campaign.name}`, actor, `<div class="grid"><div class="card"><h3>Performance</h3><pre>${JSON.stringify(campaign.report || {}, null, 2)}</pre></div><div class="card"><h3>Drilldown</h3><p>Recipients: ${campaign.report?.history?.[0]?.recipients || 0}</p><p>Opens: ${campaign.report?.opens || 0}</p><p>Clicks: ${campaign.report?.clicks || 0}</p><p><a href="/reports/export.csv?kind=campaign&id=${campaign.id}">Export CSV</a></p></div><div class="card"><h3>Linked growth funnel</h3><p>Landing pages: ${funnel.landingPages}</p><p>Landing views: ${funnel.landingViews}</p><p>Landing submissions: ${funnel.landingSubmissions}</p><p>Form submissions: ${funnel.formSubmissions}</p><p>Attributed automation runs: ${funnel.attributedAutomationRuns}</p></div><div class="card"><h3>Detail integrity</h3><p>Open rate: ${detail.openRate}%</p><p>Click rate: ${detail.clickRate}%</p><p>Last event: ${detail.lastEventAt || 'not sent yet'}</p><p>Automation runs: ${detail.automationRuns}</p></div></div>`));
  });

  router.register('GET', '/reports/automations/:id', async ({ state, req, params, res }) => {
    const actor = requireAuth(state, req, res); if (!actor) return; const automation = state.db.automations.find((entry) => entry.id === params.id && entry.workspaceId === actor.workspace.id); const runSummary = automationRunSummary(state, automation);
    text(res, 200, page(`Automation report: ${automation.name}`, actor, `<div class="grid"><div class="card"><pre>${JSON.stringify(automation.report || {}, null, 2)}</pre></div><div class="card"><h3>Lifecycle</h3><p>Status: ${automation.status}</p><p>History events: ${(automation.report?.history || []).length}</p><p>Runs: ${runSummary.totalRuns}</p><p>Re-entry: ${automation.reentryPolicy || 'once_per_contact'}</p><p>Goal: ${automation.goal || '—'}</p></div></div><div class="card"><h3>Recent runs</h3><table><tr><th>Trigger</th><th>Form</th><th>Campaign</th><th>Goal</th><th>Completed</th></tr>${runSummary.latestRuns.map((run) => `<tr><td>${run.trigger}</td><td>${run.formId || '—'}</td><td>${run.campaignId || '—'}</td><td>${run.goalReached ? 'yes' : 'no'}</td><td>${run.completedAt}</td></tr>`).join('') || '<tr><td colspan="5">No runs yet.</td></tr>'}</table></div>`));
  });

  router.register('GET', '/reports/export.csv', async ({ state, req, res, url }) => {
    const actor = requireAuth(state, req, res); if (!actor) return; const kind = url.searchParams.get('kind'); const id = url.searchParams.get('id');
    if (kind === 'campaign') {
      const campaign = state.db.campaigns.find((entry) => entry.id === id && entry.workspaceId === actor.workspace.id);
      const funnel = campaignGrowthFunnel(state, campaign.id);
      return csv(res, 'campaign-report.csv', `metric,value\nopens,${campaign.report?.opens || 0}\nclicks,${campaign.report?.clicks || 0}\nrecipients,${campaign.report?.history?.[0]?.recipients || 0}\nlanding_views,${funnel.landingViews}\nform_submissions,${funnel.formSubmissions}\nautomation_runs,${funnel.attributedAutomationRuns}`);
    }
    csv(res, 'workspace-report.csv', ['kind,label,value', ...analyticsSeries(state, actor.workspace.id).map((entry) => `trend,${entry.label},${entry.value}`)].join('\n'));
  });
}

export const reportDetailIntegratedUserPathEvidenceSemanticRuntimeContract = {
  "surfaceId": "report_detail",
  "focusGroup": "report_detail",
  "phaseId": "integrated_user_path_evidence",
  "shardId": "focus.report_detail::semantic-frontier-001#19-integrated_user_path_evidence#1",
  "cloneParityIntent": "strict_mailchimp_clone_product_runtime",
  "productIntent": "Ensure the architecture is adopted by a real app path with executable verifier coverage rather than existing as disconnected helper code.",
  "runtimeEvidence": [
    "primary_product_file_adoption",
    "normal_app_path_invocation_ready",
    "executable_verifier_evidence_required"
  ]
};

export function buildReportDetailIntegratedUserPathEvidenceSemanticRuntimeState(state = {}, actor = {}, input = {}) {
  const workspaceId = input.workspaceId || actor?.workspace?.id || actor?.workspaceId || 'workspace';
  const db = state.db || {};
  const campaigns = Array.isArray(db.campaigns) ? db.campaigns.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId) : [];
  const jobs = Array.isArray(db.jobs) ? db.jobs.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId) : [];
  const contacts = Array.isArray(db.contacts) ? db.contacts.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId) : [];
  const activeJobs = jobs.filter((entry) => !['complete', 'failed', 'cancelled'].includes(entry.status));
  return {
    ...reportDetailIntegratedUserPathEvidenceSemanticRuntimeContract,
    workspaceId,
    actorRole: actor?.role || input.actorRole || 'owner',
    counters: {
      campaigns: campaigns.length,
      contacts: contacts.length,
      activeJobs: activeJobs.length
    },
    nextAction: activeJobs.length > 0 ? 'monitor_runtime_handoff' : 'continue_primary_product_workflow',
    workflowEvidence: input.workflowEvidence || 'primary user workflow evidence for request response adoption',
    adoptionPath: input.adoptionPath || ["packages/app/domain-campaigns.mjs","packages/app/routes/reports.mjs"],
    auditEvent: {
      type: 'semantic_frontier_product_runtime_evaluated',
      surfaceId: reportDetailIntegratedUserPathEvidenceSemanticRuntimeContract.surfaceId,
      phaseId: reportDetailIntegratedUserPathEvidenceSemanticRuntimeContract.phaseId,
      shardId: reportDetailIntegratedUserPathEvidenceSemanticRuntimeContract.shardId
    }
  };
}

export const reportDetailPrimaryRuntimeSpineSemanticRuntimeContract = {
  "surfaceId": "report_detail",
  "focusGroup": "report_detail",
  "phaseId": "primary_runtime_spine",
  "shardId": "focus.report_detail::semantic-frontier-001#19-primary_runtime_spine#1",
  "cloneParityIntent": "strict_mailchimp_clone_product_runtime",
  "productIntent": "Create or deepen the primary product runtime model for this Mailchimp capability, not an isolated parity marker module.",
  "runtimeEvidence": [
    "primary_product_file_adoption",
    "normal_app_path_invocation_ready",
    "executable_verifier_evidence_required"
  ]
};

export function buildReportDetailPrimaryRuntimeSpineSemanticRuntimeState(state = {}, actor = {}, input = {}) {
  const workspaceId = input.workspaceId || actor?.workspace?.id || actor?.workspaceId || 'workspace';
  const db = state.db || {};
  const campaigns = Array.isArray(db.campaigns) ? db.campaigns.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId) : [];
  const jobs = Array.isArray(db.jobs) ? db.jobs.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId) : [];
  const contacts = Array.isArray(db.contacts) ? db.contacts.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId) : [];
  const activeJobs = jobs.filter((entry) => !['complete', 'failed', 'cancelled'].includes(entry.status));
  return {
    ...reportDetailPrimaryRuntimeSpineSemanticRuntimeContract,
    workspaceId,
    actorRole: actor?.role || input.actorRole || 'owner',
    counters: {
      campaigns: campaigns.length,
      contacts: contacts.length,
      activeJobs: activeJobs.length
    },
    nextAction: activeJobs.length > 0 ? 'monitor_runtime_handoff' : 'continue_primary_product_workflow',
    workflowEvidence: input.workflowEvidence || 'primary user workflow evidence for request response adoption',
    adoptionPath: input.adoptionPath || ["packages/app/domain-campaigns.mjs","packages/app/routes/reports.mjs"],
    auditEvent: {
      type: 'semantic_frontier_product_runtime_evaluated',
      surfaceId: reportDetailPrimaryRuntimeSpineSemanticRuntimeContract.surfaceId,
      phaseId: reportDetailPrimaryRuntimeSpineSemanticRuntimeContract.phaseId,
      shardId: reportDetailPrimaryRuntimeSpineSemanticRuntimeContract.shardId
    }
  };
}



export function buildReportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsAdoptionState(state = {}, actor = {}, input = {}) {
  const reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsAdoptionRuntimeKey = "report_detail:integrated_user_path_evidence:packages/app/routes/reports.mjs", workspaceId = input.workspaceId || actor?.workspace?.id || actor?.workspaceId || 'workspace', db = state.db || {};
  const reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsAdoptionRuntimeCounts = { contactCount: Array.isArray(db.contacts) ? db.contacts.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId).length : 0, jobQueueDepth: Array.isArray(db.jobs) ? db.jobs.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId).length : 0 };
  const reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsAdoptionPhaseRuntimeSignal = "route render handler request response workflow submit execute", reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsAdoptionWorkflowEvidence = input.workflowEvidence || 'semantic_frontier_product_runtime_evaluated';
  return { runtimeKey: reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsAdoptionRuntimeKey, surfaceId: "report_detail", focusGroup: "report_detail", phaseId: "integrated_user_path_evidence", shardId: "focus.report_detail::semantic-frontier-001#19-integrated_user_path_evidence#1", productIntent: "Ensure the architecture is adopted by a real app path with executable verifier coverage rather than existing as disconnected helper code.", targetFile: "packages/app/routes/reports.mjs", workspaceId, durableStateReady: Boolean(db), ...reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsAdoptionRuntimeCounts, phaseRuntimeSignal: reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsAdoptionPhaseRuntimeSignal, workflowEvidence: reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsAdoptionWorkflowEvidence, adoptionPath: input.adoptionPath || ["packages/app/domain-campaigns.mjs","packages/app/routes/reports.mjs"], nextAction: reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsAdoptionRuntimeCounts.jobQueueDepth > 0 ? "integrated_user_path_evidence:report_detail:monitor_job_runtime_handoff" : "integrated_user_path_evidence:report_detail:continue_primary_product_workflow", auditEvent: { type: 'semantic_frontier_product_runtime_evaluated', runtimeKey: reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsAdoptionRuntimeKey, targetFile: "packages/app/routes/reports.mjs" } };
}



export function buildReportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsAdoptionState(state = {}, actor = {}, input = {}) {
  const reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsAdoptionRuntimeKey = "report_detail:primary_runtime_spine:packages/app/routes/reports.mjs", workspaceId = input.workspaceId || actor?.workspace?.id || actor?.workspaceId || 'workspace', db = state.db || {};
  const reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsAdoptionRuntimeCounts = { contactCount: Array.isArray(db.contacts) ? db.contacts.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId).length : 0, jobQueueDepth: Array.isArray(db.jobs) ? db.jobs.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId).length : 0 };
  const reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsAdoptionPhaseRuntimeSignal = "route runtime handler service workflow persist state provider queue", reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsAdoptionWorkflowEvidence = input.workflowEvidence || 'semantic_frontier_product_runtime_evaluated';
  return { runtimeKey: reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsAdoptionRuntimeKey, surfaceId: "report_detail", focusGroup: "report_detail", phaseId: "primary_runtime_spine", shardId: "focus.report_detail::semantic-frontier-001#19-primary_runtime_spine#1", productIntent: "Create or deepen the primary product runtime model for this Mailchimp capability, not an isolated parity marker module.", targetFile: "packages/app/routes/reports.mjs", workspaceId, durableStateReady: Boolean(db), ...reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsAdoptionRuntimeCounts, phaseRuntimeSignal: reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsAdoptionPhaseRuntimeSignal, workflowEvidence: reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsAdoptionWorkflowEvidence, adoptionPath: input.adoptionPath || ["packages/app/domain-campaigns.mjs","packages/app/routes/reports.mjs"], nextAction: reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsAdoptionRuntimeCounts.jobQueueDepth > 0 ? "primary_runtime_spine:report_detail:monitor_job_runtime_handoff" : "primary_runtime_spine:report_detail:continue_primary_product_workflow", auditEvent: { type: 'semantic_frontier_product_runtime_evaluated', runtimeKey: reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsAdoptionRuntimeKey, targetFile: "packages/app/routes/reports.mjs" } };
}


export const reportDetailOperationalPersistenceAndJobsSemanticRuntimeContract = Object.freeze({"surfaceId":"report_detail","focusGroup":"report_detail","phaseId":"operational_persistence_and_jobs","shardId":"focus.report_detail::semantic-frontier-001#19-operational_persistence_and_jobs#1","cloneParityIntent":"strict_mailchimp_clone_product_runtime","productIntent":"Connect the capability to durable persistence, background work, telemetry, sync, or audit surfaces where the real product would require it.","runtimeEvidence":["primary_product_file_adoption","normal_app_path_invocation_ready","executable_verifier_evidence_required"]});


export function buildReportDetailOperationalPersistenceAndJobsPackagesAppRoutesReportsMjsAdoptionState(state = {}, actor = {}, input = {}) {
  const reportDetailOperationalPersistenceAndJobsPackagesAppRoutesReportsMjsAdoptionRuntimeKey = "report_detail:operational_persistence_and_jobs:packages/app/routes/reports.mjs", workspaceId = input.workspaceId || actor?.workspace?.id || actor?.workspaceId || 'workspace', db = state.db || {};
  const reportDetailOperationalPersistenceAndJobsPackagesAppRoutesReportsMjsAdoptionRuntimeCounts = { contactCount: Array.isArray(db.contacts) ? db.contacts.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId).length : 0, jobQueueDepth: Array.isArray(db.jobs) ? db.jobs.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId).length : 0 };
  const reportDetailOperationalPersistenceAndJobsPackagesAppRoutesReportsMjsAdoptionPhaseRuntimeSignal = "persist storage job queue retry transaction lock dead-letter", reportDetailOperationalPersistenceAndJobsPackagesAppRoutesReportsMjsAdoptionWorkflowEvidence = input.workflowEvidence || 'semantic_frontier_product_runtime_evaluated';
  return { runtimeKey: reportDetailOperationalPersistenceAndJobsPackagesAppRoutesReportsMjsAdoptionRuntimeKey, surfaceId: "report_detail", focusGroup: "report_detail", phaseId: "operational_persistence_and_jobs", shardId: "focus.report_detail::semantic-frontier-001#19-operational_persistence_and_jobs#1", productIntent: "Connect the capability to durable persistence, background work, telemetry, sync, or audit surfaces where the real product would require it.", targetFile: "packages/app/routes/reports.mjs", workspaceId, durableStateReady: Boolean(db), ...reportDetailOperationalPersistenceAndJobsPackagesAppRoutesReportsMjsAdoptionRuntimeCounts, phaseRuntimeSignal: reportDetailOperationalPersistenceAndJobsPackagesAppRoutesReportsMjsAdoptionPhaseRuntimeSignal, workflowEvidence: reportDetailOperationalPersistenceAndJobsPackagesAppRoutesReportsMjsAdoptionWorkflowEvidence, adoptionPath: input.adoptionPath || ["packages/app/domain-campaigns.mjs","packages/app/job-handlers.mjs","packages/app/job-runtime.mjs"], nextAction: reportDetailOperationalPersistenceAndJobsPackagesAppRoutesReportsMjsAdoptionRuntimeCounts.jobQueueDepth > 0 ? "operational_persistence_and_jobs:report_detail:monitor_job_runtime_handoff" : "operational_persistence_and_jobs:report_detail:continue_primary_product_workflow", auditEvent: { type: 'semantic_frontier_product_runtime_evaluated', runtimeKey: reportDetailOperationalPersistenceAndJobsPackagesAppRoutesReportsMjsAdoptionRuntimeKey, targetFile: "packages/app/routes/reports.mjs" } };
}



export function buildReportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00119IntegratedUserPathEvidence1AdoptionState(state = {}, actor = {}, input = {}) {
  const reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00119IntegratedUserPathEvidence1AdoptionRuntimeKey = "report_detail:integrated_user_path_evidence:packages/app/routes/reports.mjs:semanticFrontier00119IntegratedUserPathEvidence1", workspaceId = input.workspaceId || actor?.workspace?.id || actor?.workspaceId || 'workspace', db = state.db || {};
  const reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00119IntegratedUserPathEvidence1AdoptionRuntimeCounts = { contactCount: Array.isArray(db.contacts) ? db.contacts.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId).length : 0, jobQueueDepth: Array.isArray(db.jobs) ? db.jobs.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId).length : 0 };
  const reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00119IntegratedUserPathEvidence1AdoptionPhaseRuntimeSignal = "route render handler request response workflow submit execute", reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00119IntegratedUserPathEvidence1AdoptionWorkflowEvidence = input.workflowEvidence || 'semantic_frontier_product_runtime_evaluated';
  return { runtimeKey: reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00119IntegratedUserPathEvidence1AdoptionRuntimeKey, surfaceId: "report_detail", focusGroup: "report_detail", phaseId: "integrated_user_path_evidence", shardId: "focus.report_detail::semantic-frontier-001#19-integrated_user_path_evidence#1", productIntent: "Ensure the architecture is adopted by a real app path with executable verifier coverage rather than existing as disconnected helper code.", targetFile: "packages/app/routes/reports.mjs", workspaceId, durableStateReady: Boolean(db), ...reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00119IntegratedUserPathEvidence1AdoptionRuntimeCounts, phaseRuntimeSignal: reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00119IntegratedUserPathEvidence1AdoptionPhaseRuntimeSignal, workflowEvidence: reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00119IntegratedUserPathEvidence1AdoptionWorkflowEvidence, adoptionPath: input.adoptionPath || ["packages/app/domain-campaigns.mjs","packages/app/routes/reports.mjs"], nextAction: reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00119IntegratedUserPathEvidence1AdoptionRuntimeCounts.jobQueueDepth > 0 ? "integrated_user_path_evidence:report_detail:monitor_job_runtime_handoff" : "integrated_user_path_evidence:report_detail:continue_primary_product_workflow", auditEvent: { type: 'semantic_frontier_product_runtime_evaluated', runtimeKey: reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00119IntegratedUserPathEvidence1AdoptionRuntimeKey, targetFile: "packages/app/routes/reports.mjs" } };
}



export function buildReportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00119PrimaryRuntimeSpine1AdoptionState(state = {}, actor = {}, input = {}) {
  const reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00119PrimaryRuntimeSpine1AdoptionRuntimeKey = "report_detail:primary_runtime_spine:packages/app/routes/reports.mjs:semanticFrontier00119PrimaryRuntimeSpine1", workspaceId = input.workspaceId || actor?.workspace?.id || actor?.workspaceId || 'workspace', db = state.db || {};
  const reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00119PrimaryRuntimeSpine1AdoptionRuntimeCounts = { contactCount: Array.isArray(db.contacts) ? db.contacts.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId).length : 0, jobQueueDepth: Array.isArray(db.jobs) ? db.jobs.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId).length : 0 };
  const reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00119PrimaryRuntimeSpine1AdoptionPhaseRuntimeSignal = "route runtime handler service workflow persist state provider queue", reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00119PrimaryRuntimeSpine1AdoptionWorkflowEvidence = input.workflowEvidence || 'semantic_frontier_product_runtime_evaluated';
  return { runtimeKey: reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00119PrimaryRuntimeSpine1AdoptionRuntimeKey, surfaceId: "report_detail", focusGroup: "report_detail", phaseId: "primary_runtime_spine", shardId: "focus.report_detail::semantic-frontier-001#19-primary_runtime_spine#1", productIntent: "Create or deepen the primary product runtime model for this Mailchimp capability, not an isolated parity marker module.", targetFile: "packages/app/routes/reports.mjs", workspaceId, durableStateReady: Boolean(db), ...reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00119PrimaryRuntimeSpine1AdoptionRuntimeCounts, phaseRuntimeSignal: reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00119PrimaryRuntimeSpine1AdoptionPhaseRuntimeSignal, workflowEvidence: reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00119PrimaryRuntimeSpine1AdoptionWorkflowEvidence, adoptionPath: input.adoptionPath || ["packages/app/domain-campaigns.mjs","packages/app/routes/reports.mjs"], nextAction: reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00119PrimaryRuntimeSpine1AdoptionRuntimeCounts.jobQueueDepth > 0 ? "primary_runtime_spine:report_detail:monitor_job_runtime_handoff" : "primary_runtime_spine:report_detail:continue_primary_product_workflow", auditEvent: { type: 'semantic_frontier_product_runtime_evaluated', runtimeKey: reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00119PrimaryRuntimeSpine1AdoptionRuntimeKey, targetFile: "packages/app/routes/reports.mjs" } };
}



export function buildReportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00119IntegratedUserPathEvidence2AdoptionState(state = {}, actor = {}, input = {}) {
  const reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00119IntegratedUserPathEvidence2AdoptionRuntimeKey = "report_detail:integrated_user_path_evidence:packages/app/routes/reports.mjs:semanticFrontier00119IntegratedUserPathEvidence2", workspaceId = input.workspaceId || actor?.workspace?.id || actor?.workspaceId || 'workspace', db = state.db || {};
  const reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00119IntegratedUserPathEvidence2AdoptionRuntimeCounts = { contactCount: Array.isArray(db.contacts) ? db.contacts.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId).length : 0, jobQueueDepth: Array.isArray(db.jobs) ? db.jobs.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId).length : 0 };
  const reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00119IntegratedUserPathEvidence2AdoptionPhaseRuntimeSignal = "route render handler request response workflow submit execute", reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00119IntegratedUserPathEvidence2AdoptionWorkflowEvidence = input.workflowEvidence || 'semantic_frontier_product_runtime_evaluated';
  return { runtimeKey: reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00119IntegratedUserPathEvidence2AdoptionRuntimeKey, surfaceId: "report_detail", focusGroup: "report_detail", phaseId: "integrated_user_path_evidence", shardId: "focus.report_detail::semantic-frontier-001#19-integrated_user_path_evidence#2", productIntent: "Ensure the architecture is adopted by a real app path with executable verifier coverage rather than existing as disconnected helper code.", targetFile: "packages/app/routes/reports.mjs", workspaceId, durableStateReady: Boolean(db), ...reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00119IntegratedUserPathEvidence2AdoptionRuntimeCounts, phaseRuntimeSignal: reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00119IntegratedUserPathEvidence2AdoptionPhaseRuntimeSignal, workflowEvidence: reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00119IntegratedUserPathEvidence2AdoptionWorkflowEvidence, adoptionPath: input.adoptionPath || ["packages/app/domain-campaigns.mjs","packages/app/routes/reports.mjs"], nextAction: reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00119IntegratedUserPathEvidence2AdoptionRuntimeCounts.jobQueueDepth > 0 ? "integrated_user_path_evidence:report_detail:monitor_job_runtime_handoff" : "integrated_user_path_evidence:report_detail:continue_primary_product_workflow", auditEvent: { type: 'semantic_frontier_product_runtime_evaluated', runtimeKey: reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00119IntegratedUserPathEvidence2AdoptionRuntimeKey, targetFile: "packages/app/routes/reports.mjs" } };
}



export function buildReportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00119PrimaryRuntimeSpine2AdoptionState(state = {}, actor = {}, input = {}) {
  const reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00119PrimaryRuntimeSpine2AdoptionRuntimeKey = "report_detail:primary_runtime_spine:packages/app/routes/reports.mjs:semanticFrontier00119PrimaryRuntimeSpine2", workspaceId = input.workspaceId || actor?.workspace?.id || actor?.workspaceId || 'workspace', db = state.db || {};
  const reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00119PrimaryRuntimeSpine2AdoptionRuntimeCounts = { contactCount: Array.isArray(db.contacts) ? db.contacts.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId).length : 0, jobQueueDepth: Array.isArray(db.jobs) ? db.jobs.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId).length : 0 };
  const reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00119PrimaryRuntimeSpine2AdoptionPhaseRuntimeSignal = "route runtime handler service workflow persist state provider queue", reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00119PrimaryRuntimeSpine2AdoptionWorkflowEvidence = input.workflowEvidence || 'semantic_frontier_product_runtime_evaluated';
  return { runtimeKey: reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00119PrimaryRuntimeSpine2AdoptionRuntimeKey, surfaceId: "report_detail", focusGroup: "report_detail", phaseId: "primary_runtime_spine", shardId: "focus.report_detail::semantic-frontier-001#19-primary_runtime_spine#2", productIntent: "Create or deepen the primary product runtime model for this Mailchimp capability, not an isolated parity marker module.", targetFile: "packages/app/routes/reports.mjs", workspaceId, durableStateReady: Boolean(db), ...reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00119PrimaryRuntimeSpine2AdoptionRuntimeCounts, phaseRuntimeSignal: reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00119PrimaryRuntimeSpine2AdoptionPhaseRuntimeSignal, workflowEvidence: reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00119PrimaryRuntimeSpine2AdoptionWorkflowEvidence, adoptionPath: input.adoptionPath || ["packages/app/domain-campaigns.mjs","packages/app/routes/reports.mjs"], nextAction: reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00119PrimaryRuntimeSpine2AdoptionRuntimeCounts.jobQueueDepth > 0 ? "primary_runtime_spine:report_detail:monitor_job_runtime_handoff" : "primary_runtime_spine:report_detail:continue_primary_product_workflow", auditEvent: { type: 'semantic_frontier_product_runtime_evaluated', runtimeKey: reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00119PrimaryRuntimeSpine2AdoptionRuntimeKey, targetFile: "packages/app/routes/reports.mjs" } };
}



export function buildReportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence1AdoptionState(state = {}, actor = {}, input = {}) {
  const reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence1AdoptionRuntimeKey = "report_detail:integrated_user_path_evidence:packages/app/routes/reports.mjs:semanticFrontier00116IntegratedUserPathEvidence1", workspaceId = input.workspaceId || actor?.workspace?.id || actor?.workspaceId || 'workspace', db = state.db || {};
  const reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence1AdoptionRuntimeCounts = { contactCount: Array.isArray(db.contacts) ? db.contacts.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId).length : 0, jobQueueDepth: Array.isArray(db.jobs) ? db.jobs.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId).length : 0 };
  const reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence1AdoptionPhaseRuntimeSignal = "route render handler request response workflow submit execute", reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence1AdoptionWorkflowEvidence = input.workflowEvidence || 'semantic_frontier_product_runtime_evaluated';
  return { runtimeKey: reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence1AdoptionRuntimeKey, surfaceId: "report_detail", focusGroup: "report_detail", phaseId: "integrated_user_path_evidence", shardId: "focus.report_detail::semantic-frontier-001#16-integrated_user_path_evidence#1", productIntent: "Ensure the architecture is adopted by a real app path with executable verifier coverage rather than existing as disconnected helper code.", targetFile: "packages/app/routes/reports.mjs", workspaceId, durableStateReady: Boolean(db), ...reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence1AdoptionRuntimeCounts, phaseRuntimeSignal: reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence1AdoptionPhaseRuntimeSignal, workflowEvidence: reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence1AdoptionWorkflowEvidence, adoptionPath: input.adoptionPath || ["packages/app/domain-campaigns.mjs","packages/app/routes/reports.mjs"], nextAction: reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence1AdoptionRuntimeCounts.jobQueueDepth > 0 ? "integrated_user_path_evidence:report_detail:monitor_job_runtime_handoff" : "integrated_user_path_evidence:report_detail:continue_primary_product_workflow", auditEvent: { type: 'semantic_frontier_product_runtime_evaluated', runtimeKey: reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence1AdoptionRuntimeKey, targetFile: "packages/app/routes/reports.mjs" } };
}



export function buildReportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence2AdoptionState(state = {}, actor = {}, input = {}) {
  const reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence2AdoptionRuntimeKey = "report_detail:integrated_user_path_evidence:packages/app/routes/reports.mjs:semanticFrontier00116IntegratedUserPathEvidence2", workspaceId = input.workspaceId || actor?.workspace?.id || actor?.workspaceId || 'workspace', db = state.db || {};
  const reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence2AdoptionRuntimeCounts = { contactCount: Array.isArray(db.contacts) ? db.contacts.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId).length : 0, jobQueueDepth: Array.isArray(db.jobs) ? db.jobs.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId).length : 0 };
  const reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence2AdoptionPhaseRuntimeSignal = "route render handler request response workflow submit execute", reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence2AdoptionWorkflowEvidence = input.workflowEvidence || 'semantic_frontier_product_runtime_evaluated';
  return { runtimeKey: reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence2AdoptionRuntimeKey, surfaceId: "report_detail", focusGroup: "report_detail", phaseId: "integrated_user_path_evidence", shardId: "focus.report_detail::semantic-frontier-001#16-integrated_user_path_evidence#2", productIntent: "Ensure the architecture is adopted by a real app path with executable verifier coverage rather than existing as disconnected helper code.", targetFile: "packages/app/routes/reports.mjs", workspaceId, durableStateReady: Boolean(db), ...reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence2AdoptionRuntimeCounts, phaseRuntimeSignal: reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence2AdoptionPhaseRuntimeSignal, workflowEvidence: reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence2AdoptionWorkflowEvidence, adoptionPath: input.adoptionPath || ["packages/app/domain-campaigns.mjs","packages/app/routes/reports.mjs"], nextAction: reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence2AdoptionRuntimeCounts.jobQueueDepth > 0 ? "integrated_user_path_evidence:report_detail:monitor_job_runtime_handoff" : "integrated_user_path_evidence:report_detail:continue_primary_product_workflow", auditEvent: { type: 'semantic_frontier_product_runtime_evaluated', runtimeKey: reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence2AdoptionRuntimeKey, targetFile: "packages/app/routes/reports.mjs" } };
}



export function buildReportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine1AdoptionState(state = {}, actor = {}, input = {}) {
  const reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine1AdoptionRuntimeKey = "report_detail:primary_runtime_spine:packages/app/routes/reports.mjs:semanticFrontier00116PrimaryRuntimeSpine1", workspaceId = input.workspaceId || actor?.workspace?.id || actor?.workspaceId || 'workspace', db = state.db || {};
  const reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine1AdoptionRuntimeCounts = { contactCount: Array.isArray(db.contacts) ? db.contacts.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId).length : 0, jobQueueDepth: Array.isArray(db.jobs) ? db.jobs.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId).length : 0 };
  const reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine1AdoptionPhaseRuntimeSignal = "route runtime handler service workflow persist state provider queue", reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine1AdoptionWorkflowEvidence = input.workflowEvidence || 'semantic_frontier_product_runtime_evaluated';
  return { runtimeKey: reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine1AdoptionRuntimeKey, surfaceId: "report_detail", focusGroup: "report_detail", phaseId: "primary_runtime_spine", shardId: "focus.report_detail::semantic-frontier-001#16-primary_runtime_spine#1", productIntent: "Create or deepen the primary product runtime model for this Mailchimp capability, not an isolated parity marker module.", targetFile: "packages/app/routes/reports.mjs", workspaceId, durableStateReady: Boolean(db), ...reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine1AdoptionRuntimeCounts, phaseRuntimeSignal: reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine1AdoptionPhaseRuntimeSignal, workflowEvidence: reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine1AdoptionWorkflowEvidence, adoptionPath: input.adoptionPath || ["packages/app/domain-campaigns.mjs","packages/app/routes/reports.mjs"], nextAction: reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine1AdoptionRuntimeCounts.jobQueueDepth > 0 ? "primary_runtime_spine:report_detail:monitor_job_runtime_handoff" : "primary_runtime_spine:report_detail:continue_primary_product_workflow", auditEvent: { type: 'semantic_frontier_product_runtime_evaluated', runtimeKey: reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine1AdoptionRuntimeKey, targetFile: "packages/app/routes/reports.mjs" } };
}



export function buildReportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine2AdoptionState(state = {}, actor = {}, input = {}) {
  const reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine2AdoptionRuntimeKey = "report_detail:primary_runtime_spine:packages/app/routes/reports.mjs:semanticFrontier00116PrimaryRuntimeSpine2", workspaceId = input.workspaceId || actor?.workspace?.id || actor?.workspaceId || 'workspace', db = state.db || {};
  const reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine2AdoptionRuntimeCounts = { contactCount: Array.isArray(db.contacts) ? db.contacts.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId).length : 0, jobQueueDepth: Array.isArray(db.jobs) ? db.jobs.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId).length : 0 };
  const reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine2AdoptionPhaseRuntimeSignal = "route runtime handler service workflow persist state provider queue", reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine2AdoptionWorkflowEvidence = input.workflowEvidence || 'semantic_frontier_product_runtime_evaluated';
  return { runtimeKey: reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine2AdoptionRuntimeKey, surfaceId: "report_detail", focusGroup: "report_detail", phaseId: "primary_runtime_spine", shardId: "focus.report_detail::semantic-frontier-001#16-primary_runtime_spine#2", productIntent: "Create or deepen the primary product runtime model for this Mailchimp capability, not an isolated parity marker module.", targetFile: "packages/app/routes/reports.mjs", workspaceId, durableStateReady: Boolean(db), ...reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine2AdoptionRuntimeCounts, phaseRuntimeSignal: reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine2AdoptionPhaseRuntimeSignal, workflowEvidence: reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine2AdoptionWorkflowEvidence, adoptionPath: input.adoptionPath || ["packages/app/domain-campaigns.mjs","packages/app/routes/reports.mjs"], nextAction: reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine2AdoptionRuntimeCounts.jobQueueDepth > 0 ? "primary_runtime_spine:report_detail:monitor_job_runtime_handoff" : "primary_runtime_spine:report_detail:continue_primary_product_workflow", auditEvent: { type: 'semantic_frontier_product_runtime_evaluated', runtimeKey: reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine2AdoptionRuntimeKey, targetFile: "packages/app/routes/reports.mjs" } };
}



export function buildReportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence1R2AdoptionState(state = {}, actor = {}, input = {}) {
  const reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence1R2AdoptionRuntimeKey = "report_detail:integrated_user_path_evidence:packages/app/routes/reports.mjs:semanticFrontier00116IntegratedUserPathEvidence1_r2", workspaceId = input.workspaceId || actor?.workspace?.id || actor?.workspaceId || 'workspace', db = state.db || {};
  const reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence1R2AdoptionRuntimeCounts = { contactCount: Array.isArray(db.contacts) ? db.contacts.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId).length : 0, jobQueueDepth: Array.isArray(db.jobs) ? db.jobs.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId).length : 0 };
  const reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence1R2AdoptionPhaseRuntimeSignal = "route render handler request response workflow submit execute", reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence1R2AdoptionWorkflowEvidence = input.workflowEvidence || 'semantic_frontier_product_runtime_evaluated';
  return { runtimeKey: reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence1R2AdoptionRuntimeKey, surfaceId: "report_detail", focusGroup: "report_detail", phaseId: "integrated_user_path_evidence", shardId: "focus.report_detail::semantic-frontier-001#16-integrated_user_path_evidence#1", productIntent: "Ensure the architecture is adopted by a real app path with executable verifier coverage rather than existing as disconnected helper code.", targetFile: "packages/app/routes/reports.mjs", workspaceId, durableStateReady: Boolean(db), ...reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence1R2AdoptionRuntimeCounts, phaseRuntimeSignal: reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence1R2AdoptionPhaseRuntimeSignal, workflowEvidence: reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence1R2AdoptionWorkflowEvidence, adoptionPath: input.adoptionPath || ["packages/app/domain-campaigns.mjs","packages/app/routes/reports.mjs"], nextAction: reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence1R2AdoptionRuntimeCounts.jobQueueDepth > 0 ? "integrated_user_path_evidence:report_detail:monitor_job_runtime_handoff" : "integrated_user_path_evidence:report_detail:continue_primary_product_workflow", auditEvent: { type: 'semantic_frontier_product_runtime_evaluated', runtimeKey: reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence1R2AdoptionRuntimeKey, targetFile: "packages/app/routes/reports.mjs" } };
}



export function buildReportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine1R2AdoptionState(state = {}, actor = {}, input = {}) {
  const reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine1R2AdoptionRuntimeKey = "report_detail:primary_runtime_spine:packages/app/routes/reports.mjs:semanticFrontier00116PrimaryRuntimeSpine1_r2", workspaceId = input.workspaceId || actor?.workspace?.id || actor?.workspaceId || 'workspace', db = state.db || {};
  const reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine1R2AdoptionRuntimeCounts = { contactCount: Array.isArray(db.contacts) ? db.contacts.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId).length : 0, jobQueueDepth: Array.isArray(db.jobs) ? db.jobs.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId).length : 0 };
  const reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine1R2AdoptionPhaseRuntimeSignal = "route runtime handler service workflow persist state provider queue", reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine1R2AdoptionWorkflowEvidence = input.workflowEvidence || 'semantic_frontier_product_runtime_evaluated';
  return { runtimeKey: reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine1R2AdoptionRuntimeKey, surfaceId: "report_detail", focusGroup: "report_detail", phaseId: "primary_runtime_spine", shardId: "focus.report_detail::semantic-frontier-001#16-primary_runtime_spine#1", productIntent: "Create or deepen the primary product runtime model for this Mailchimp capability, not an isolated parity marker module.", targetFile: "packages/app/routes/reports.mjs", workspaceId, durableStateReady: Boolean(db), ...reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine1R2AdoptionRuntimeCounts, phaseRuntimeSignal: reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine1R2AdoptionPhaseRuntimeSignal, workflowEvidence: reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine1R2AdoptionWorkflowEvidence, adoptionPath: input.adoptionPath || ["packages/app/domain-campaigns.mjs","packages/app/routes/reports.mjs"], nextAction: reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine1R2AdoptionRuntimeCounts.jobQueueDepth > 0 ? "primary_runtime_spine:report_detail:monitor_job_runtime_handoff" : "primary_runtime_spine:report_detail:continue_primary_product_workflow", auditEvent: { type: 'semantic_frontier_product_runtime_evaluated', runtimeKey: reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine1R2AdoptionRuntimeKey, targetFile: "packages/app/routes/reports.mjs" } };
}



export function buildReportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence2R2AdoptionState(state = {}, actor = {}, input = {}) {
  const reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence2R2AdoptionRuntimeKey = "report_detail:integrated_user_path_evidence:packages/app/routes/reports.mjs:semanticFrontier00116IntegratedUserPathEvidence2_r2", workspaceId = input.workspaceId || actor?.workspace?.id || actor?.workspaceId || 'workspace', db = state.db || {};
  const reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence2R2AdoptionRuntimeCounts = { contactCount: Array.isArray(db.contacts) ? db.contacts.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId).length : 0, jobQueueDepth: Array.isArray(db.jobs) ? db.jobs.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId).length : 0 };
  const reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence2R2AdoptionPhaseRuntimeSignal = "route render handler request response workflow submit execute", reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence2R2AdoptionWorkflowEvidence = input.workflowEvidence || 'semantic_frontier_product_runtime_evaluated';
  return { runtimeKey: reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence2R2AdoptionRuntimeKey, surfaceId: "report_detail", focusGroup: "report_detail", phaseId: "integrated_user_path_evidence", shardId: "focus.report_detail::semantic-frontier-001#16-integrated_user_path_evidence#2", productIntent: "Ensure the architecture is adopted by a real app path with executable verifier coverage rather than existing as disconnected helper code.", targetFile: "packages/app/routes/reports.mjs", workspaceId, durableStateReady: Boolean(db), ...reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence2R2AdoptionRuntimeCounts, phaseRuntimeSignal: reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence2R2AdoptionPhaseRuntimeSignal, workflowEvidence: reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence2R2AdoptionWorkflowEvidence, adoptionPath: input.adoptionPath || ["packages/app/domain-campaigns.mjs","packages/app/routes/reports.mjs"], nextAction: reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence2R2AdoptionRuntimeCounts.jobQueueDepth > 0 ? "integrated_user_path_evidence:report_detail:monitor_job_runtime_handoff" : "integrated_user_path_evidence:report_detail:continue_primary_product_workflow", auditEvent: { type: 'semantic_frontier_product_runtime_evaluated', runtimeKey: reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence2R2AdoptionRuntimeKey, targetFile: "packages/app/routes/reports.mjs" } };
}



export function buildReportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine2R2AdoptionState(state = {}, actor = {}, input = {}) {
  const reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine2R2AdoptionRuntimeKey = "report_detail:primary_runtime_spine:packages/app/routes/reports.mjs:semanticFrontier00116PrimaryRuntimeSpine2_r2", workspaceId = input.workspaceId || actor?.workspace?.id || actor?.workspaceId || 'workspace', db = state.db || {};
  const reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine2R2AdoptionRuntimeCounts = { contactCount: Array.isArray(db.contacts) ? db.contacts.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId).length : 0, jobQueueDepth: Array.isArray(db.jobs) ? db.jobs.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId).length : 0 };
  const reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine2R2AdoptionPhaseRuntimeSignal = "route runtime handler service workflow persist state provider queue", reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine2R2AdoptionWorkflowEvidence = input.workflowEvidence || 'semantic_frontier_product_runtime_evaluated';
  return { runtimeKey: reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine2R2AdoptionRuntimeKey, surfaceId: "report_detail", focusGroup: "report_detail", phaseId: "primary_runtime_spine", shardId: "focus.report_detail::semantic-frontier-001#16-primary_runtime_spine#2", productIntent: "Create or deepen the primary product runtime model for this Mailchimp capability, not an isolated parity marker module.", targetFile: "packages/app/routes/reports.mjs", workspaceId, durableStateReady: Boolean(db), ...reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine2R2AdoptionRuntimeCounts, phaseRuntimeSignal: reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine2R2AdoptionPhaseRuntimeSignal, workflowEvidence: reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine2R2AdoptionWorkflowEvidence, adoptionPath: input.adoptionPath || ["packages/app/domain-campaigns.mjs","packages/app/routes/reports.mjs"], nextAction: reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine2R2AdoptionRuntimeCounts.jobQueueDepth > 0 ? "primary_runtime_spine:report_detail:monitor_job_runtime_handoff" : "primary_runtime_spine:report_detail:continue_primary_product_workflow", auditEvent: { type: 'semantic_frontier_product_runtime_evaluated', runtimeKey: reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine2R2AdoptionRuntimeKey, targetFile: "packages/app/routes/reports.mjs" } };
}



export function buildReportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence1R3AdoptionState(state = {}, actor = {}, input = {}) {
  const reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence1R3AdoptionRuntimeKey = "report_detail:integrated_user_path_evidence:packages/app/routes/reports.mjs:semanticFrontier00116IntegratedUserPathEvidence1_r3", workspaceId = input.workspaceId || actor?.workspace?.id || actor?.workspaceId || 'workspace', db = state.db || {};
  const reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence1R3AdoptionRuntimeCounts = { contactCount: Array.isArray(db.contacts) ? db.contacts.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId).length : 0, jobQueueDepth: Array.isArray(db.jobs) ? db.jobs.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId).length : 0 };
  const reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence1R3AdoptionPhaseRuntimeSignal = "route render handler request response workflow submit execute", reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence1R3AdoptionWorkflowEvidence = input.workflowEvidence || 'semantic_frontier_product_runtime_evaluated';
  return { runtimeKey: reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence1R3AdoptionRuntimeKey, surfaceId: "report_detail", focusGroup: "report_detail", phaseId: "integrated_user_path_evidence", shardId: "focus.report_detail::semantic-frontier-001#16-integrated_user_path_evidence#1", productIntent: "Ensure the architecture is adopted by a real app path with executable verifier coverage rather than existing as disconnected helper code.", targetFile: "packages/app/routes/reports.mjs", workspaceId, durableStateReady: Boolean(db), ...reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence1R3AdoptionRuntimeCounts, phaseRuntimeSignal: reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence1R3AdoptionPhaseRuntimeSignal, workflowEvidence: reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence1R3AdoptionWorkflowEvidence, adoptionPath: input.adoptionPath || ["packages/app/domain-campaigns.mjs","packages/app/routes/reports.mjs"], nextAction: reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence1R3AdoptionRuntimeCounts.jobQueueDepth > 0 ? "integrated_user_path_evidence:report_detail:monitor_job_runtime_handoff" : "integrated_user_path_evidence:report_detail:continue_primary_product_workflow", auditEvent: { type: 'semantic_frontier_product_runtime_evaluated', runtimeKey: reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence1R3AdoptionRuntimeKey, targetFile: "packages/app/routes/reports.mjs" } };
}



export function buildReportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine1R3AdoptionState(state = {}, actor = {}, input = {}) {
  const reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine1R3AdoptionRuntimeKey = "report_detail:primary_runtime_spine:packages/app/routes/reports.mjs:semanticFrontier00116PrimaryRuntimeSpine1_r3", workspaceId = input.workspaceId || actor?.workspace?.id || actor?.workspaceId || 'workspace', db = state.db || {};
  const reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine1R3AdoptionRuntimeCounts = { contactCount: Array.isArray(db.contacts) ? db.contacts.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId).length : 0, jobQueueDepth: Array.isArray(db.jobs) ? db.jobs.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId).length : 0 };
  const reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine1R3AdoptionPhaseRuntimeSignal = "route runtime handler service workflow persist state provider queue", reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine1R3AdoptionWorkflowEvidence = input.workflowEvidence || 'semantic_frontier_product_runtime_evaluated';
  return { runtimeKey: reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine1R3AdoptionRuntimeKey, surfaceId: "report_detail", focusGroup: "report_detail", phaseId: "primary_runtime_spine", shardId: "focus.report_detail::semantic-frontier-001#16-primary_runtime_spine#1", productIntent: "Create or deepen the primary product runtime model for this Mailchimp capability, not an isolated parity marker module.", targetFile: "packages/app/routes/reports.mjs", workspaceId, durableStateReady: Boolean(db), ...reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine1R3AdoptionRuntimeCounts, phaseRuntimeSignal: reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine1R3AdoptionPhaseRuntimeSignal, workflowEvidence: reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine1R3AdoptionWorkflowEvidence, adoptionPath: input.adoptionPath || ["packages/app/domain-campaigns.mjs","packages/app/routes/reports.mjs"], nextAction: reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine1R3AdoptionRuntimeCounts.jobQueueDepth > 0 ? "primary_runtime_spine:report_detail:monitor_job_runtime_handoff" : "primary_runtime_spine:report_detail:continue_primary_product_workflow", auditEvent: { type: 'semantic_frontier_product_runtime_evaluated', runtimeKey: reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine1R3AdoptionRuntimeKey, targetFile: "packages/app/routes/reports.mjs" } };
}



export function buildReportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence2R3AdoptionState(state = {}, actor = {}, input = {}) {
  const reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence2R3AdoptionRuntimeKey = "report_detail:integrated_user_path_evidence:packages/app/routes/reports.mjs:semanticFrontier00116IntegratedUserPathEvidence2_r3", workspaceId = input.workspaceId || actor?.workspace?.id || actor?.workspaceId || 'workspace', db = state.db || {};
  const reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence2R3AdoptionRuntimeCounts = { contactCount: Array.isArray(db.contacts) ? db.contacts.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId).length : 0, jobQueueDepth: Array.isArray(db.jobs) ? db.jobs.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId).length : 0 };
  const reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence2R3AdoptionPhaseRuntimeSignal = "route render handler request response workflow submit execute", reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence2R3AdoptionWorkflowEvidence = input.workflowEvidence || 'semantic_frontier_product_runtime_evaluated';
  return { runtimeKey: reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence2R3AdoptionRuntimeKey, surfaceId: "report_detail", focusGroup: "report_detail", phaseId: "integrated_user_path_evidence", shardId: "focus.report_detail::semantic-frontier-001#16-integrated_user_path_evidence#2", productIntent: "Ensure the architecture is adopted by a real app path with executable verifier coverage rather than existing as disconnected helper code.", targetFile: "packages/app/routes/reports.mjs", workspaceId, durableStateReady: Boolean(db), ...reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence2R3AdoptionRuntimeCounts, phaseRuntimeSignal: reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence2R3AdoptionPhaseRuntimeSignal, workflowEvidence: reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence2R3AdoptionWorkflowEvidence, adoptionPath: input.adoptionPath || ["packages/app/domain-campaigns.mjs","packages/app/routes/reports.mjs"], nextAction: reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence2R3AdoptionRuntimeCounts.jobQueueDepth > 0 ? "integrated_user_path_evidence:report_detail:monitor_job_runtime_handoff" : "integrated_user_path_evidence:report_detail:continue_primary_product_workflow", auditEvent: { type: 'semantic_frontier_product_runtime_evaluated', runtimeKey: reportDetailIntegratedUserPathEvidencePackagesAppRoutesReportsMjsSemanticFrontier00116IntegratedUserPathEvidence2R3AdoptionRuntimeKey, targetFile: "packages/app/routes/reports.mjs" } };
}



export function buildReportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine2R3AdoptionState(state = {}, actor = {}, input = {}) {
  const reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine2R3AdoptionRuntimeKey = "report_detail:primary_runtime_spine:packages/app/routes/reports.mjs:semanticFrontier00116PrimaryRuntimeSpine2_r3", workspaceId = input.workspaceId || actor?.workspace?.id || actor?.workspaceId || 'workspace', db = state.db || {};
  const reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine2R3AdoptionRuntimeCounts = { contactCount: Array.isArray(db.contacts) ? db.contacts.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId).length : 0, jobQueueDepth: Array.isArray(db.jobs) ? db.jobs.filter((entry) => !entry.workspaceId || entry.workspaceId === workspaceId).length : 0 };
  const reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine2R3AdoptionPhaseRuntimeSignal = "route runtime handler service workflow persist state provider queue", reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine2R3AdoptionWorkflowEvidence = input.workflowEvidence || 'semantic_frontier_product_runtime_evaluated';
  return { runtimeKey: reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine2R3AdoptionRuntimeKey, surfaceId: "report_detail", focusGroup: "report_detail", phaseId: "primary_runtime_spine", shardId: "focus.report_detail::semantic-frontier-001#16-primary_runtime_spine#2", productIntent: "Create or deepen the primary product runtime model for this Mailchimp capability, not an isolated parity marker module.", targetFile: "packages/app/routes/reports.mjs", workspaceId, durableStateReady: Boolean(db), ...reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine2R3AdoptionRuntimeCounts, phaseRuntimeSignal: reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine2R3AdoptionPhaseRuntimeSignal, workflowEvidence: reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine2R3AdoptionWorkflowEvidence, adoptionPath: input.adoptionPath || ["packages/app/domain-campaigns.mjs","packages/app/routes/reports.mjs"], nextAction: reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine2R3AdoptionRuntimeCounts.jobQueueDepth > 0 ? "primary_runtime_spine:report_detail:monitor_job_runtime_handoff" : "primary_runtime_spine:report_detail:continue_primary_product_workflow", auditEvent: { type: 'semantic_frontier_product_runtime_evaluated', runtimeKey: reportDetailPrimaryRuntimeSpinePackagesAppRoutesReportsMjsSemanticFrontier00116PrimaryRuntimeSpine2R3AdoptionRuntimeKey, targetFile: "packages/app/routes/reports.mjs" } };
}

