"""
The Darwin Loop - Self-Optimization for The Cortex.
CRITICAL FIX: Requires human approval before deployment.
Non-blocking revision: uses async HTTP and thread offload for filesystem/compile work.
"""
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import Optional
import httpx
import subprocess
import os
import tempfile
import asyncio

router = APIRouter()

# Internal API endpoints
ORACLE_URL = "http://localhost:8888/oracle/chat"
BASE_DIR = "/app/cortex_server"
ORACLE_TIMEOUT = 25.0


class EvolveRequest(BaseModel):
    target_file: str
    issue: str
    auto_approve: bool = False  # CRITICAL: Default to False


class EvolveResponse(BaseModel):
    status: str
    message: str
    target_file: str
    validation_result: Optional[str]
    approval_required: bool = True


def read_target_file(file_path: str) -> str:
    full_path = os.path.join(BASE_DIR, file_path)
    if not os.path.exists(full_path):
        raise FileNotFoundError(f"Target file not found: {file_path}")
    with open(full_path, "r") as f:
        return f.read()


async def consult_oracle(current_code: str, issue: str) -> str:
    system_prompt = """You are an expert Python programmer. Your task is to refactor code to fix the specified issue.
Rules:
1. Return ONLY valid Python code (no markdown, no explanations)
2. Maintain the same file structure and imports
3. Ensure the code is syntactically correct
4. Keep the router and endpoint definitions intact
5. Focus on the specific issue mentioned"""

    oracle_payload = {
        "prompt": f"Current code:\n```\n{current_code[:2000]}\n```\n\nIssue to fix: {issue}\n\nProvide the refactored Python code:",
        "system": system_prompt,
        "model": "tinyllama"
    }

    async with httpx.AsyncClient(timeout=ORACLE_TIMEOUT) as client:
        resp = await client.post(ORACLE_URL, json=oracle_payload)
        resp.raise_for_status()
        response_text = resp.json().get("response", "")

    if "```python" in response_text:
        code = response_text.split("```python")[1].split("```")[0].strip()
    elif "```" in response_text:
        code = response_text.split("```")[1].split("```")[0].strip()
    else:
        code = response_text.strip()

    return code


def validate_code(code: str) -> tuple[bool, str]:
    temp_path = None
    try:
        with tempfile.NamedTemporaryFile(mode="w", suffix=".py", delete=False) as f:
            f.write(code)
            temp_path = f.name

        subprocess.run(["python3", "-m", "py_compile", temp_path], check=True, capture_output=True, text=True)
        return True, "Code syntax is valid"
    except subprocess.CalledProcessError as e:
        error = e.stderr if e.stderr else str(e)
        return False, f"Syntax error: {error}"
    except Exception as e2:
        return False, f"Validation failed: {str(e2)}"
    finally:
        if temp_path and os.path.exists(temp_path):
            try:
                os.unlink(temp_path)
            except Exception:
                pass


async def request_human_approval(target_file: str, issue: str, new_code: str) -> bool:
    """Request human approval via Diplomat; fail closed (False)."""
    try:
        preview = new_code[:500] + "..." if len(new_code) > 500 else new_code
        approval_request = f"""Darwin Loop requests approval to modify:

File: {target_file}
Issue: {issue}

Code Preview:
{preview}

This change was generated by AI and requires your approval before deployment."""

        async with httpx.AsyncClient(timeout=5.0) as client:
            await client.post("http://localhost:8888/diplomat/test", json={"message": approval_request})
        return False
    except Exception:
        return False


def deploy_patch(file_path: str, new_code: str) -> bool:
    full_path = os.path.join(BASE_DIR, file_path)
    with open(full_path, "w") as f:
        f.write(new_code)
    return True


@router.post("/evolve", response_model=EvolveResponse)
async def darwin_evolve(request: EvolveRequest):
    try:
        current_code = await asyncio.to_thread(read_target_file, request.target_file)
    except FileNotFoundError as e:
        raise HTTPException(status_code=404, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Read failed: {str(e)}")

    try:
        new_code = await consult_oracle(current_code, request.issue)
        if not new_code.strip():
            raise HTTPException(status_code=500, detail="Oracle returned empty code")
    except httpx.TimeoutException:
        raise HTTPException(status_code=504, detail="Oracle consultation timed out")
    except Exception as e:
        raise HTTPException(status_code=503, detail=f"Oracle consultation failed: {str(e)}")

    is_valid, validation_msg = await asyncio.to_thread(validate_code, new_code)

    if not is_valid:
        return EvolveResponse(
            status="rejected",
            message=f"Code validation failed: {validation_msg}",
            target_file=request.target_file,
            validation_result=validation_msg,
            approval_required=False,
        )

    if not request.auto_approve:
        approved = await request_human_approval(request.target_file, request.issue, new_code)
        if not approved:
            return EvolveResponse(
                status="pending_approval",
                message="Code validated but requires human approval before deployment. Use auto_approve=true only in emergencies.",
                target_file=request.target_file,
                validation_result=validation_msg,
                approval_required=True,
            )

    try:
        await asyncio.to_thread(deploy_patch, request.target_file, new_code)
        return EvolveResponse(
            status="evolved",
            message=f"Successfully patched {request.target_file} (auto_approved={request.auto_approve})",
            target_file=request.target_file,
            validation_result=validation_msg,
            approval_required=False,
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Deployment failed: {str(e)}")


@router.get("/status")
async def darwin_status():
    services = {}
    async with httpx.AsyncClient(timeout=2.0) as client:
        try:
            resp = await client.get("http://localhost:8888/oracle/status")
            services["oracle"] = "online" if resp.status_code == 200 else "offline"
        except Exception:
            services["oracle"] = "offline"

        try:
            resp = await client.get("http://localhost:8888/lab/execute")
            services["lab"] = "online" if resp.status_code in [200, 422] else "offline"
        except Exception:
            services["lab"] = "offline"

    return {
        "status": "active",
        "services": services,
        "capabilities": ["code_read", "oracle_consult", "syntax_validate", "human_approval", "deploy_patch"],
        "security": "HUMAN_APPROVAL_REQUIRED",
        "version": "12.2-ASYNC-SAFE",
    }
